name_map = {
    "NBA": {
        "New York": "New York Knicks",
        "Los Angeles": "Los Angeles Lakers",
        "Chicago": "Chicago Bulls",
        "Miami": "Miami Heat",
        "Boston": "Boston Celtics",
        "Philadelphia": "Philadelphia 76ers",
        "Golden State": "Golden State Warriors",
        "Dallas": "Dallas Mavericks",
        "Toronto": "Toronto Raptors",
        "Phoenix": "Phoenix Suns",
        "Milwaukee": "Milwaukee Bucks",
        "Utah": "Utah Jazz",
        "Denver": "Denver Nuggets",
        "Sacramento": "Sacramento Kings",
        "Oklahoma City": "Oklahoma City Thunder",
        "Memphis": "Memphis Grizzlies",
        "Charlotte": "Charlotte Hornets",
        "Indiana": "Indiana Pacers",
        "Washington": "Washington Wizards",
        "Brooklyn": "Brooklyn Nets",
        "Atlanta": "Atlanta Hawks",
        "Orlando": "Orlando Magic",
        "Minnesota": "Minnesota Timberwolves",
        "New Orleans": "New Orleans Pelicans",
        "Detroit": "Detroit Pistons",
        "Houston": "Houston Rockets",
        "San Antonio": "San Antonio Spurs",
        "Cleveland": "Cleveland Cavaliers",
    },
    "NFL": {
        "Arizona": "Arizona Cardinals",
        "Atlanta": "Atlanta Falcons",
        "Baltimore": "Baltimore Ravens",
        "Buffalo": "Buffalo Bills",
        "Carolina": "Carolina Panthers",
        "Chicago": "Chicago Bears",
        "Cincinnati": "Cincinnati Bengals",
        "Cleveland": "Cleveland Browns",
        "Dallas": "Dallas Cowboys",
        "Denver": "Denver Broncos",
        "Detroit": "Detroit Lions",
        "Green Bay": "Green Bay Packers",
        "Houston": "Houston Texans",
        "Indianapolis": "Indianapolis Colts",
        "Jacksonville": "Jacksonville Jaguars",
        "Kansas City": "Kansas City Chiefs",
        "Las Vegas": "Las Vegas Raiders",
        "Los Angeles R": "Los Angeles Rams",
        "Los Angeles C": "Los Angeles Chargers",
        "Miami": "Miami Dolphins",
        "Minnesota": "Minnesota Vikings",
        "New England": "New England Patriots",
        "New Orleans": "New Orleans Saints",
        "New York": "New York Giants",
        "Philadelphia": "Philadelphia Eagles",
        "Pittsburgh": "Pittsburgh Steelers",
        "San Francisco": "San Francisco 49ers",
        "Seattle": "Seattle Seahawks",
        "Tampa Bay": "Tampa Bay Buccaneers",
        "Tennessee": "Tennessee Titans",
        "Washington": "Washington Commanders",
    },
    "WNBA": {
        "Atlanta": "Atlanta Dream",
        "Chicago": "Chicago Sky",
        "Connecticut": "Connecticut Sun",
        "Dallas": "Dallas Wings",
        "Indiana": "Indiana Fever",
        "Las Vegas": "Las Vegas Aces",
        "Golden State": "Golden State Valkyries",
        "Minnesota": "Minnesota Lynx",
        "New York": "New York Liberty",
        "Phoenix": "Phoenix Mercury",
        "Seattle": "Seattle Storm",
        "Washington": "Washington Mystics",
    },
    "MLB": {
        "Arizona": "Arizona Diamondbacks",
        "Atlanta": "Atlanta Braves",
        "Baltimore": "Baltimore Orioles",
        "Boston": "Boston Red Sox",
        "Chicago C": "Chicago Cubs",
        "Chicago WS": "Chicago White Sox",
        "Cincinnati": "Cincinnati Reds",
        "Cleveland": "Cleveland Guardians",
        "Colorado": "Colorado Rockies",
        "Detroit": "Detroit Tigers",
        "Houston": "Houston Astros",
        "Kansas City": "Kansas City Royals",
        "Los Angeles D": "Los Angeles Dodgers",
        "Miami": "Miami Marlins",
        "Milwaukee": "Milwaukee Brewers",
        "Minnesota": "Minnesota Twins",
        "New York M": "New York Mets",
        "New York Y": "New York Yankees",
        "Oakland": "Oakland Athletics",
        "Philadelphia": "Philadelphia Phillies",
        "Pittsburgh": "Pittsburgh Pirates",
        "San Diego": "San Diego Padres",
        "San Francisco": "San Francisco Giants",
        "Seattle": "Seattle Mariners",
        "St. Louis": "St. Louis Cardinals",
        "Tampa Bay": "Tampa Bay Rays",
        "Texas": "Texas Rangers",
        "Toronto": "Toronto Blue Jays",
        "Washington": "Washington Nationals",
    },
    "NHL": {
        "Vegas Golden Knights": "Las Vegas Golden Knights",
    },
    "College Football": {
        "Ohio St.": "Ohio State",
        "Penn St.": "Penn State",
        "Miami (FL)": "U Miami"
    }
}